float x = 250;
float y = 250;
float a = 255;
float b = 255;
float c = 255;
float z = 255;
float playerdmg= -1;
int playerlvl =1;
int exp = 0;
boolean run = false;
boolean left = false;
boolean up = false;
boolean down = true;
boolean right = false;
int startMillis;
int levelMillis;
int attackduration = 1;
int temp;
int coincount;
PImage coinimg;
boolean Scene2 = false;
boolean Scene1 = false;
boolean Scene3 = false;
boolean Scene4 = false;
boolean MenuScene = true;
int pos = 300;
boolean Scene2enter = true;
boolean Scene3enter = false;
String [] chatter = {"Emilie: Why do you get to be player one?","Emilie: I'm out of Mana!","Emilie: We have to find the King Slime!","Emilie: For Monsters they are pretty cute!"};
  String[] chatter2 = {"Emilie: It's cold ><","Emilie: We must be getting close","Emilie: We have to find the King Slime!","Emilie: Okay, these guys are scary!"};
boolean dialoguebox = false;
boolean toggle = false;
boolean gameover = false;
TFextbox box1;
TFextbox box2;
int sentence2;

coins[] coin;
coins[] coins2;
slime[] slim2;
elite[] elites;
emilie em;
slime[] slim;
king boss;
HealthBar hb0;
